### PR TITLE
Adding Group functionality

### PR DESCRIPTION
**Pull request by miker1423**
Hello, I wrote some methods to add the functionality of groups, it is in a very basic form.

### CODE REVIEW

**Comment by radu-matei** [comment]
Hi!
Thank you very much for the contribution you provided so far!

Sorry for delaying this, I have been focusing on different projects lately, but I would love to get back working on this.
In order to do this, I would love to enable you people to contribute directly to the projects. Please let me know if you want to be granted write access to branches of this repo.

Thanks,
Radu M

**Comment by radu-matei** [comment]
Looks great, thanks!
Will try to review later this week.

cc @mihai-burduselu

**Comment by miker1423** [comment]
Thanks!

**Review by mihai-burduselu — APPROVED** [review]

**Comment by radu-matei** [comment]
Merged #38

**Pull request merged**
